
- name: reboot machine to make ssd work
  shell: sleep 10 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay="{{delay}}" timeout="{{timeout}}" port="{{port}}"
  sudo: false
