
- name: reboot machine
  shell: sudo sleep 10 && sudo shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay="{{delay}}" timeout="{{timeout}}" port="{{port}}"
  become: false
