
- name: reboot machine
  shell: shutdown -r now
  async: 1
  poll: 0

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay="{{delay}}" timeout="{{timeout}}" port="{{port}}"
  become: false
