- stat: path=/var/local/ansible-first-run
  register: already_ran

- name: reboot machine to make ssd work
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  sudo: true
  ignore_errors: true
  when: already_ran.stat.exists == false or reboot_on_first_run_only == false

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay="{{delay}}" timeout="{{timeout}}" port="{{port}}"
  sudo: false
  when: already_ran.stat.exists == false or reboot_on_first_run_only == false
  
- file: path="/var/local/ansible-first-run" mode=0644 state=touch